import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  docs: [
    {
      dirName: ".",
      type: "autogenerated",
    },
  ],
}

export default sidebars
